### ISSUE TITLE
Projects and Namespaces

### ISSUE THREAD

**Issue by neutmute** [neutmute/swimbait#4]
@rmarinho The projects and namespaces I started with could use do with a tidy up before we get further in.
I've penned an initial idea on this [wiki page ](https://github.com/neutmute/swimbait/wiki) so you can jump in and edit and make comments/suggestions.

Thoughts?
The ClientBridge project I added because I thought you will need that to call the client from node.
Is that right?

**Comment by rmarinho** [comment]
Yeah, that's what i m doing tonight, the final integration with homebridge to see if i can get the service to show up on HomeKit. That should be something like MusicCast.Homebridge .. but it's a nodejs project. still figuring if i will need or not the server in the middle, or i will try get [Edge.js](http://tjanczuk.github.io/edge/#/)

**Comment by neutmute** [comment]
You have a nice cross section of technologies on this project!

I've updated the projects and namespaces to be a bit more consistent.
