### ISSUE TITLE
MusicCast API

### ISSUE THREAD

**Issue by NovaGL** [neutmute/swimbait#7]
Public API is now available!

https://jayvee.com.au/downloads/commands/yamaha/YXC_API_Spec_Basic.pdf

**Comment by neutmute** [comment]
Nice work! I've mirrored it into this repo and updated the readme.
Also promising:

> Yamaha  Extended  Control  API  Specification (Advanced) will be released on Oct 2016.

**Comment by deadbone** [comment]
Hi
Do you know where the Yamaha Extended Control API Specification (Advanced) can be found ? 
Regards

**Comment by simeoncode** [comment]
Would be awesome to find the advanced specification. Here is a function list that I found while hunting around for the advanced API specification: https://jayvee.com.au/downloads/commands/yamaha/YXC_Function_list_v1.0.pdf

**Comment by simeoncode** [comment]
Found it! https://www.pdf-archive.com/2017/04/21/yxc-api-spec-advanced/

**Comment by neutmute** [comment]
good work! have archived it here in the `doc` folder

**Comment by uSpike** [comment]
Sorry if this is the wrong place, but I don't know where else to ask.  It seems that in neither the basic or advanced API docs they reference the `secure/` endpoint.  Is it critical to correctly respond to these requests in order to correctly pair as a speaker?

Awesome project!

**Comment by neutmute** [comment]
I didn't respond to `secure` in this project and I have paired a speaker but not yet transmitted music to it...so, so far it isn't critical.
From memory, the secure part was for credentials for music services like Pandora.
